// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LeaderboardTeam
    {
        /// <summary>
        /// Initializes a new instance of the LeaderboardTeam class.
        /// </summary>
        public LeaderboardTeam() { }

        /// <summary>
        /// Initializes a new instance of the LeaderboardTeam class.
        /// </summary>
        public LeaderboardTeam(int? rank = default, string? name = default, string? logo = default, int? territoryCount = default, int? playerCount = default, int? mercCount = default, double? starPower = default)
        {
            Rank = rank;
            Name = name;
            Logo = logo;
            TerritoryCount = territoryCount;
            PlayerCount = playerCount;
            MercCount = mercCount;
            StarPower = starPower;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int? Rank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string? Name { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logo")]
        public string? Logo { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "territoryCount")]
        public int? TerritoryCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "playerCount")]
        public int? PlayerCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mercCount")]
        public int? MercCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "starPower")]
        public double? StarPower { get; set; }

    }
}
