// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TeamPlayerLastTurn
    {
        /// <summary>
        /// Initializes a new instance of the TeamPlayerLastTurn class.
        /// </summary>
        public TeamPlayerLastTurn() { }

        /// <summary>
        /// Initializes a new instance of the TeamPlayerLastTurn class.
        /// </summary>
        public TeamPlayerLastTurn(int? season = default(int?), int? day = default(int?), int? stars = default(int?))
        {
            Season = season;
            Day = day;
            Stars = stars;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "season")]
        public int? Season { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "day")]
        public int? Day { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stars")]
        public int? Stars { get; set; }

    }
}
