// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TeamColors
    {
        /// <summary>
        /// Initializes a new instance of the TeamColors class.
        /// </summary>
        public TeamColors() { }

        /// <summary>
        /// Initializes a new instance of the TeamColors class.
        /// </summary>
        public TeamColors(string? primary = default, string? secondary = default)
        {
            Primary = primary!;
            Secondary = secondary!;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primary")]
        public string Primary { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondary")]
        public string Secondary { get; set; } = null!;

    }
}
