// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TeamStrength
    {
        /// <summary>
        /// Initializes a new instance of the TeamStrength class.
        /// </summary>
        public TeamStrength() { }

        /// <summary>
        /// Initializes a new instance of the TeamStrength class.
        /// </summary>
        public TeamStrength(string? team = default, int? players = default, int? mercs = default, int? stars = default, int? territories = default)
        {
            Team = team;
            Players = players;
            Mercs = mercs;
            Stars = stars;
            Territories = territories;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "team")]
        public string? Team { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "players")]
        public int? Players { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mercs")]
        public int? Mercs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stars")]
        public int? Stars { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "territories")]
        public int? Territories { get; set; }

    }
}
