// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TeamPlayer
    {
        /// <summary>
        /// Initializes a new instance of the TeamPlayer class.
        /// </summary>
        public TeamPlayer() { }

        /// <summary>
        /// Initializes a new instance of the TeamPlayer class.
        /// </summary>
        public TeamPlayer(string? team = default, string? player = default, int? turnsPlayed = default, int? mvps = default, TeamPlayerLastTurn? lastTurn = default)
        {
            Team = team;
            Player = player;
            TurnsPlayed = turnsPlayed;
            Mvps = mvps;
            LastTurn = lastTurn;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "team")]
        public string? Team { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "player")]
        public string? Player { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "turnsPlayed")]
        public int? TurnsPlayed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mvps")]
        public int? Mvps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastTurn")]
        public TeamPlayerLastTurn? LastTurn { get; set; }

    }
}
