// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TerritoryNeighborsItem
    {
        /// <summary>
        /// Initializes a new instance of the TerritoryNeighborsItem class.
        /// </summary>
        public TerritoryNeighborsItem() { }

        /// <summary>
        /// Initializes a new instance of the TerritoryNeighborsItem class.
        /// </summary>
        public TerritoryNeighborsItem(int? id = default, string? name = default, string? owner = default)
        {
            Id = id;
            Name = name;
            Owner = owner;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string? Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string? Owner { get; set; }

    }
}
