// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TerritoryTurn
    {
        /// <summary>
        /// Initializes a new instance of the TerritoryTurn class.
        /// </summary>
        public TerritoryTurn() { }

        /// <summary>
        /// Initializes a new instance of the TerritoryTurn class.
        /// </summary>
        public TerritoryTurn(string? occupier = default, string? winner = default, IList<TerritoryTurnTeamsItem>? teams = default, IList<TerritoryTurnPlayersItem>? players = default)
        {
            Occupier = occupier!;
            Winner = winner!;
            Teams = teams!;
            Players = players!;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "occupier")]
        public string Occupier { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "winner")]
        public string Winner { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teams")]
        public IList<TerritoryTurnTeamsItem> Teams { get; set; } = null!;

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "players")]
        public IList<TerritoryTurnPlayersItem> Players { get; set; } = null!;

    }
}
