// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TerritoryTurnTeamsItem
    {
        /// <summary>
        /// Initializes a new instance of the TerritoryTurnTeamsItem class.
        /// </summary>
        public TerritoryTurnTeamsItem() { }

        /// <summary>
        /// Initializes a new instance of the TerritoryTurnTeamsItem class.
        /// </summary>
        public TerritoryTurnTeamsItem(string? team = default, string? color = default, string? secondaryColor = default, int? players = default, int? power = default, double? chance = default, TerritoryTurnTeamsItemBreakdown? breakdown = default)
        {
            Team = team;
            Color = color;
            SecondaryColor = secondaryColor;
            Players = players;
            Power = power;
            Chance = chance;
            Breakdown = breakdown;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "team")]
        public string? Team { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string? Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondaryColor")]
        public string? SecondaryColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "players")]
        public int? Players { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "power")]
        public int? Power { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chance")]
        public double? Chance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "breakdown")]
        public TerritoryTurnTeamsItemBreakdown? Breakdown { get; set; }

    }
}
