// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Territory
    {
        /// <summary>
        /// Initializes a new instance of the Territory class.
        /// </summary>
        public Territory() { }

        /// <summary>
        /// Initializes a new instance of the Territory class.
        /// </summary>
        public Territory(int? id = default, string? name = default, string? shortName = default, string? owner = default, IList<TerritoryNeighborsItem>? neighbors = default)
        {
            Id = id;
            Name = name;
            ShortName = shortName;
            Owner = owner;
            Neighbors = neighbors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string? Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shortName")]
        public string? ShortName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string? Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "neighbors")]
        public IList<TerritoryNeighborsItem>? Neighbors { get; set; }

    }
}
