// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CollegeFootballRisk.InternalModels
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TerritoryHistory
    {
        /// <summary>
        /// Initializes a new instance of the TerritoryHistory class.
        /// </summary>
        public TerritoryHistory() { }

        /// <summary>
        /// Initializes a new instance of the TerritoryHistory class.
        /// </summary>
        public TerritoryHistory(int? season = default, int? day = default, string? territory = default, string? owner = default)
        {
            Season = season;
            Day = day;
            Territory = territory;
            Owner = owner;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "season")]
        public int? Season { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "day")]
        public int? Day { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "territory")]
        public string? Territory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string? Owner { get; set; }

    }
}
